# Generated by Django 4.2.5 on 2023-11-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_detecter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedurl',
            name='url',
            field=models.CharField(max_length=4000),
        ),
    ]
